{% set name = "cellxgene-census" %}
{% set last_name = "cellxgene-census" %}
{% set version = "1.10.1" %}
# shasum -a 256 of https://pypi.io/packages/source/c/cellxgene-census/cellxgene_census-i.j.k.tar.gz
{% set sha256 = "de1677ea246e6639ee05e9bdd8355be631109a477b51020ec9affc4d2f2e0f88" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ last_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8,<3.12
    - tiledbsoma-py
    - anndata
    - numpy >=1.21,<1.25
    - requests
    - typing-extensions
    - s3fs >=2021.06.1
    - scipy

test:
  imports:
    - cellxgene_census

about:
  summary: API to facilitate the use of the CZ CELLxGENE Discover Census. For more information about the API and the project visit https://github.com/chanzuckerberg/cellxgene-census/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Shelnutt2
